[package]
name = "rusty-vault"
version = "0.3.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
docopt = "*"
postgres = "*"
rust-crypto = "*"
rand = "*"
rustc-serialize = "*"
uuid = { version = "0.2.2", features = ["rustc-serialize", "v4"] }
