[package]
name = "rusty-vault"
version = "0.1.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
rust-crypto = "*"
rand = "*"

rusty-vault-storage-filesystem = { path = "storages/filesystem" }
