[package]
name = "rusty-vault"
version = "0.4.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
docopt = "*"
postgres = { version = "0.11", features = ["uuid", "rustc-serialize"] }
rust-crypto = "*"
rand = "*"
rustc-serialize = "*"
uuid = { version = "0.2.2", features = ["rustc-serialize", "v4"] }
